### ISSUE TITLE
Chamber doesn't work for some reason

### ISSUE THREAD

**Issue by Mister-SOSA** [Mister-SOSA/Valorant-Instalocker-Tool#2]
I'm working on it

**Comment by Mister-SOSA** [comment]
So far, it seems to be an issue with the API endpoint on Riot's end, but I will look further into it anyway.

**Comment by bboychris168** [comment]
You forgot to add Chamber to the "list_all_agents" dict.

**Comment by Mister-SOSA** [comment]
That's embarrassing
